# Permalinks
permalink:      pretty

# Setup
title:          Glenn's Blog
paginate:       5
baseurl:	"/"
url:            "https://glennbarrett.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Glenn Barrett
  url:          http://glennbarrett.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap
